<?php
/**
 * Created by PHPro
 *
 * @package      DPD
 * @subpackage   Shipping
 * @category     Checkout
 * @author       PHPro (info@phpro.be)
 */
/**
 * Import the api with or without key in header.
 */

$url = Mage::getSingleton('dpd/webservice')->getClientUrl();

?>
<?php if (!(bool)Mage::getStoreConfig('carriers/dpdparcelshops/gmapsDisplay')): ?>
    <script
        src="<?php echo sprintf('%s/parcelshop/map/js', $url) ?>"
        type="text/javascript"></script>
<?php endif; ?>
