<?php
/**
 * Created by PHPro
 *
 * @package      DPD
 * @subpackage   Shipping
 * @category     Checkout
 * @author       PHPro (info@phpro.be)
 */
/**
 * ParcelShop HTML
 */
?>
<?php
$quote = Mage::getSingleton('checkout/session')->getQuote();
$shippingaddress = $quote->getShippingAddress();
if(($shippingaddress->getPostcode() != "" && $shippingaddress->getPostcode() != "-") &&
($shippingaddress->getCountryId()!= "" && $shippingaddress->getCountryId()!= "-")):
$height = Mage::getStoreConfig('carriers/dpdparcelshops/google_maps_height');
$width = Mage::getStoreConfig('carriers/dpdparcelshops/google_maps_width');
$modal = Mage::getStoreConfig('carriers/dpdparcelshops/google_maps_display');
?>
<style>
    .parcelshopwrapper .shops {
        height: <?php echo $height ?>px;
    }

    .custom-panel-size {
        height: <?php echo $height ?>px;
        width: <?php echo $width ?>px;
        margin-top: <?php echo !$modal ? '10px': '0' ?>;
        display: block;
    }
</style>
<div id="parcelshop" class="parcelshopwrapper">
    <div id="dpd-connect-map-container" class="custom-panel-size">
        <div class="dpdloaderwrapper" style="margin-bottom:35px;"><span class="dpdloader"></span><span class="message"></span></div><input type="hidden" class="DPD-confirmed" value="0"/>
    </div>
    <div id="dpd-connect-selected-container" class="custom-panel-size"></div>
    <input type="hidden" class="DPD-confirmed" value="0"/>
    <script type="text/javascript">
        window.dpdconfig = <?php echo $this->getConfig(!$quote->getDpdSelected()) ?>;
        <?php if($this->getIsAjax() || Mage::getStoreConfig('carriers/dpdparcelshops/google_maps_display')): ?>
        window.dpdShipping = new DPD.Connect('DPD_window_content', window.dpdconfig);
        <?php elseif(Mage::helper('dpd')->getIsOnestepCheckout()): ?>
        window.dpdShipping = new DPD.Connect('.onestepcheckout-shipping-method', window.dpdconfig);
        <?php else: ?>
        window.dpdShipping = new DPD.Connect('checkout-shipping-method-load', window.dpdconfig);
        <?php endif; ?>
    </script>
    <div class="dpdclear"></div>
</div>
<?php endif; ?>